/**
 * FleetMind renderer — generates openclaw.json and terraform vars from fleet config.
 */

import fs from "node:fs";
import path from "node:path";
import type { Fleet, AgentConfig } from "../config/schema.js";

export function renderOpenClawJson(fleet: Fleet): Record<string, unknown> {
  const { agents, openclaw } = fleet;
  const defaults = agents.defaults;
  const oc = openclaw;

  // Agent list
  const agentList = agents.list.map((agent) => {
    const model = agent.model ?? defaults.model;
    const workspace = `${defaults.workspace_base}/workspace-${agent.id}`;
    const agentDir = `${defaults.workspace_base}/agents/${agent.id}/agent`;
    return {
      id: agent.id,
      name: agent.name,
      workspace,
      agentDir,
      model: { primary: model },
      ...(agent.orchestrator ? { default: true } : {}),
    };
  });

  // Bindings: one per agent, matched on Slack accountId
  const bindings = agents.list.map((agent) => ({
    agentId: agent.id,
    match: {
      channel: "slack",
      accountId: agent.slack.account_id,
    },
  }));

  // Slack accounts
  const slackAccounts: Record<string, unknown> = {};
  for (const agent of agents.list) {
    slackAccounts[agent.slack.account_id] = {
      enabled: true,
      botToken: agent.slack.bot_token,
      appToken: agent.slack.app_token,
      webhookPath: `/slack/${agent.slack.account_id}`,
      groupPolicy: "open",
    };
  }

  // agentToAgent allow list (deduplicated)
  const a2aAllow: Array<{ from: string; to: string }> = [];
  for (const agent of agents.list) {
    for (const targetId of agent.agent_to_agent.can_send_to) {
      if (!a2aAllow.some((e) => e.from === agent.id && e.to === targetId)) {
        a2aAllow.push({ from: agent.id, to: targetId });
      }
    }
  }

  // Collect all plugins across agents
  const allPlugins = new Set<string>();
  for (const agent of agents.list) {
    const plugins = agent.plugins ?? defaults.plugins;
    for (const p of plugins) allPlugins.add(p);
  }
  const pluginEntries: Record<string, unknown> = {};
  for (const plugin of [...allPlugins].sort()) {
    pluginEntries[plugin] = { enabled: true };
  }

  return {
    agents: {
      defaults: { model: { primary: defaults.model } },
      list: agentList,
    },
    bindings,
    tools: {
      profile: oc.tools.profile,
      agentToAgent: {
        enabled: true,
        allow: a2aAllow,
      },
      web: {
        search: {
          enabled: oc.tools.web_search.enabled,
          provider: oc.tools.web_search.provider,
        },
      },
    },
    session: {
      dmScope: oc.session.dm_scope,
    },
    channels: {
      slack: {
        mode: oc.slack.mode,
        enabled: true,
        typingReaction: oc.slack.typing_reaction,
        ackReaction: oc.slack.ack_reaction,
        allowBots: oc.slack.allow_bots,
        historyLimit: oc.slack.history_limit,
        streaming: {
          mode: oc.slack.streaming.mode,
          nativeTransport: oc.slack.streaming.native_transport,
        },
        replyToModeByChatType: {
          channel: oc.slack.reply_to_mode_by_chat_type.channel,
        },
        accounts: slackAccounts,
      },
    },
    gateway: {
      port: oc.gateway.port,
      mode: oc.gateway.mode,
      bind: oc.gateway.bind,
    },
    hooks: {
      internal: {
        enabled: true,
        entries: {
          "boot-md": { enabled: true },
          "session-memory": { enabled: true },
          "command-logger": { enabled: true },
        },
      },
    },
    plugins: {
      entries: pluginEntries,
    },
    commands: {
      native: "auto",
      nativeSkills: "auto",
      restart: true,
    },
  };
}

export function renderTerraformVars(fleet: Fleet): string {
  const agentIds = fleet.agents.list.map((a) => `"${a.id}"`).join(", ");
  const lines = [
    `# Auto-generated by FleetMind — do not edit manually`,
    `# Fleet: ${fleet.fleet.name} v${fleet.fleet.version}`,
    ``,
    `fleet_name    = "${fleet.fleet.name}"`,
    `fleet_client  = "${fleet.fleet.client}"`,
    `agent_count   = ${fleet.agents.list.length}`,
    `agent_ids     = [${agentIds}]`,
    ``,
    `# Agent model assignments`,
    ...fleet.agents.list.map((a) => {
      const model = a.model ?? fleet.agents.defaults.model;
      return `agent_${a.id}_model = "${model}"`;
    }),
  ];
  return lines.join("\n") + "\n";
}

export function writeOutputs(
  fleet: Fleet,
  baseDir: string = "."
): Record<string, string> {
  const written: Record<string, string> = {};

  // openclaw.json
  const ocPath = path.resolve(baseDir, fleet.outputs.openclaw_json);
  fs.mkdirSync(path.dirname(ocPath), { recursive: true });
  fs.writeFileSync(ocPath, JSON.stringify(renderOpenClawJson(fleet), null, 2));
  written["openclaw_json"] = ocPath;

  // terraform vars
  const tfPath = path.resolve(baseDir, fleet.outputs.terraform_vars);
  fs.mkdirSync(path.dirname(tfPath), { recursive: true });
  fs.writeFileSync(tfPath, renderTerraformVars(fleet));
  written["terraform_vars"] = tfPath;

  return written;
}
