# Auto-generated by FleetMind — do not edit manually
# Fleet: test-fleet v1.0.0

fleet_name  = "test-fleet"
agent_names = ["conductor"]

# OpenClaw runtime ownership. Default is infrastructure/root managed;
# opt-in installs an exact seed version into a dedicated service-owned prefix.
openclaw_runtime_mode = "root-managed"

# PM (orchestrator) flag per agent — drives task-ledger IAM policy split.
agent_orchestrators = {
  "conductor" = true
}

# Per-agent model providers (drives per-provider Secrets Manager secrets
# at <fleet>/agents/<agent>/providers/<provider>). REQUIRED.
agent_providers = {
  "conductor" = []
}

# Explicit GitHub Apps per agent. This grants IAM only: no credentials enter Terraform.
agent_github_apps = {
  "conductor" = []
}

# NOTE: instance_type, aws_region, and other infrastructure vars are not
# derived from fleet.yaml — set them in your workspace tfvars manually.
# See infra/terraform/variables.tf for all available variables.
