# Auto-generated by FleetMind — do not edit manually
# Fleet: test-fleet v1.0.0

fleet_name  = "test-fleet"
agent_names = ["conductor"]

# PM (orchestrator) flag per agent — drives task-ledger IAM policy split.
agent_orchestrators = {
  conductor = true
}

# Per-agent gateway ports (sequential from 18789). Override in workspaces/*.tfvars
# if you need specific ports.
agent_ports = {
  conductor = 18789
}

# Wake target derived from the PM agent's first Slack channel. Used by the
# task-ledger EventBridge target to SSM-invoke the PM on terminal task events.
# Empty until the PM's slack.channels is populated in fleet.yaml.
wake_target_session_key = ""

# NOTE: instance_type, aws_region, and other infrastructure vars are not
# derived from fleet.yaml — set them in your workspace tfvars manually.
# See infra/terraform/variables.tf for all available variables.
