"""
FleetMind CLI — deploy and manage OpenClaw multi-agent fleets.

Commands:
  init        Scaffold a new fleet.yaml
  deploy      Provision agent workspaces from fleet.yaml
  diff        Show what would change without applying
  render      Emit openclaw.json + terraform vars without deploying
  push        Push skills or plugins to agents
  watch       GitOps watcher — auto-push skill updates from skills repo
  status      Show fleet status
  agent       Manage individual agents
  secrets     Manage fleet secrets
"""

import json
import os
import shutil
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.table import Table
from rich.panel import Panel

app = typer.Typer(
    name="fleetmind",
    help="FleetMind — deploy and manage OpenClaw multi-agent fleets",
    no_args_is_help=True,
)
push_app = typer.Typer(help="Push skills or plugins to agents", no_args_is_help=True)
agent_app = typer.Typer(help="Manage individual agents", no_args_is_help=True)
secrets_app = typer.Typer(help="Manage fleet secrets", no_args_is_help=True)

app.add_typer(push_app, name="push")
app.add_typer(agent_app, name="agent")
app.add_typer(secrets_app, name="secrets")

console = Console()

FLEET_YAML_TEMPLATE = """\
# fleet.yaml — FleetMind fleet definition
# Generated by: fleetmind init
#
# Fill in your values and run: fleetmind deploy

fleet:
  name: {name}
  version: "1.0.0"
  client: {client}
  description: ""

skills_repo:
  url: ""               # https://github.com/your-org/your-skills-repo
  branch: main
  poll_interval: 60s
  # local: ./skills     # Use local skills dir (dev mode)

secrets:
  provider: env

agents:
  defaults:
    model: anthropic/claude-sonnet-4-6
    workspace_base: /home/ec2-user/.openclaw
    plugins:
      - anthropic

  list:
    - id: conductor
      name: Conductor
      emoji: 🎼
      description: "Orchestrator. Routes requests to specialist agents."
      orchestrator: true
      persona:
        soul: |
          You are Conductor, an orchestrating AI that coordinates a fleet of specialists.
          Delegate to specialists via sessions_send. Synthesize results for the user.
      slack:
        account_id: conductor
        bot_token: ${{CONDUCTOR_BOT_TOKEN}}
        app_token: ${{CONDUCTOR_APP_TOKEN}}
      skills: []
      plugins: [anthropic]
      agent_to_agent:
        can_send_to: []

outputs:
  openclaw_json: ./rendered/openclaw.json
  terraform_vars: ./rendered/fleet.auto.tfvars
  workspace_manifests: ./rendered/workspaces/

openclaw:
  gateway:
    port: 18789
    mode: local
    bind: loopback
  session:
    dm_scope: per-channel-peer
  tools:
    profile: coding
  slack:
    mode: socket
    typing_reaction: thinking_face
    ack_reaction: eyes
    allow_bots: true
    history_limit: 111
"""

SECRETS_FILE = Path.home() / ".openclaw" / "fleetmind-secrets.json"


def _load_secrets() -> dict:
    if SECRETS_FILE.exists():
        return json.loads(SECRETS_FILE.read_text())
    return {}


def _save_secrets(secrets: dict) -> None:
    SECRETS_FILE.parent.mkdir(parents=True, exist_ok=True)
    SECRETS_FILE.write_text(json.dumps(secrets, indent=2))
    SECRETS_FILE.chmod(0o600)


def _load_fleet(config: Path) -> "FleetConfig":  # noqa: F821
    from ..coordinator.config import FleetConfig
    if not config.exists():
        console.print(f"[red]Error:[/red] {config} not found.")
        raise typer.Exit(1)
    try:
        return FleetConfig.load(config)
    except Exception as e:
        console.print(f"[red]Error loading fleet.yaml:[/red] {e}")
        raise typer.Exit(1)


# ── Commands ──────────────────────────────────────────────────────────────────

@app.command()
def init(
    name: str = typer.Option("my-fleet", "--name", "-n", help="Fleet name"),
    client: str = typer.Option("", "--client", "-c", help="Client name"),
    output: Path = typer.Option(Path("fleet.yaml"), "--output", "-o", help="Output file"),
):
    """Scaffold a new fleet.yaml in the current directory."""
    if output.exists():
        overwrite = typer.confirm(f"{output} already exists. Overwrite?", default=False)
        if not overwrite:
            raise typer.Exit(0)

    content = FLEET_YAML_TEMPLATE.format(name=name, client=client or name)
    output.write_text(content)

    # Create rendered dir and .gitignore entry
    Path("rendered").mkdir(exist_ok=True)
    gitignore = Path(".gitignore")
    ignore_lines = ["fleet.yaml", "rendered/openclaw.json", ".env"]
    if gitignore.exists():
        existing = gitignore.read_text()
        missing = [l for l in ignore_lines if l not in existing]
        if missing:
            gitignore.write_text(existing + "\n" + "\n".join(missing) + "\n")
    else:
        gitignore.write_text("\n".join(ignore_lines) + "\n")

    console.print(f"[green]✓[/green] Created [bold]{output}[/bold]")
    console.print("\nNext steps:")
    console.print("  1. Edit fleet.yaml — add agents, Slack tokens, skills")
    console.print("  2. [bold]fleetmind secrets set CONDUCTOR_BOT_TOKEN xoxb-...[/bold]")
    console.print("  3. [bold]fleetmind deploy[/bold]")


@app.command()
def deploy(
    config: Path = typer.Argument(Path("fleet.yaml"), help="Path to fleet.yaml"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Show what would happen without doing it"),
    no_render: bool = typer.Option(False, "--no-render", help="Skip rendering openclaw.json"),
    no_restart: bool = typer.Option(False, "--no-restart", help="Skip gateway restart"),
):
    """Provision agent workspaces and render openclaw.json."""
    from ..runtime.provisioner import provision_fleet
    from ..runtime.renderer import write_outputs

    fleet = _load_fleet(config)

    if dry_run:
        console.print("[yellow]Dry run — no changes will be made.[/yellow]\n")

    provision_fleet(fleet, dry_run=dry_run)

    if not no_render:
        written = write_outputs(fleet)
        for name, path in written.items():
            console.print(f"[green]✓[/green] Rendered [bold]{name}[/bold] → {path}")

    if not no_restart and not dry_run:
        console.print("\n[dim]Tip: run [bold]openclaw gateway restart[/bold] to apply the new config.[/dim]")


@app.command()
def diff(
    config: Path = typer.Argument(Path("fleet.yaml"), help="Path to fleet.yaml"),
):
    """Show what deploy would change without applying anything."""
    from ..runtime.provisioner import diff_fleet

    fleet = _load_fleet(config)
    changes = diff_fleet(fleet)

    if changes == ["No changes detected."]:
        console.print("[green]✓ No changes detected.[/green]")
    else:
        console.print(f"[bold]Changes ({len(changes)}):[/bold]")
        for change in changes:
            if change.startswith("[+]"):
                console.print(f"  [green]{change}[/green]")
            elif change.startswith("[~]"):
                console.print(f"  [yellow]{change}[/yellow]")
            elif change.startswith("[-]"):
                console.print(f"  [red]{change}[/red]")
            else:
                console.print(f"  {change}")


@app.command()
def render(
    config: Path = typer.Argument(Path("fleet.yaml"), help="Path to fleet.yaml"),
    out: Path = typer.Option(Path("."), "--out", "-o", help="Output base directory"),
):
    """Render openclaw.json and terraform vars without deploying."""
    from ..runtime.renderer import write_outputs

    fleet = _load_fleet(config)
    written = write_outputs(fleet, base_dir=out)

    console.print(f"[bold]Rendered outputs for fleet [cyan]{fleet.name}[/cyan]:[/bold]")
    for name, path in written.items():
        console.print(f"  [green]✓[/green] {name}: [dim]{path}[/dim]")


@app.command()
def watch(
    config: Path = typer.Argument(Path("fleet.yaml"), help="Path to fleet.yaml"),
    interval: Optional[str] = typer.Option(None, "--interval", help="Poll interval (e.g. 30s, 5m)"),
):
    """GitOps watcher — auto-push skill updates from the skills repo."""
    from ..runtime.watcher import SkillsWatcher

    fleet = _load_fleet(config)
    if interval:
        fleet.skills_repo.poll_interval = interval

    watcher = SkillsWatcher(fleet)
    watcher.watch()


@app.command()
def status(
    config: Path = typer.Argument(Path("fleet.yaml"), help="Path to fleet.yaml"),
):
    """Show fleet configuration and workspace status."""
    fleet = _load_fleet(config)

    console.print(Panel(
        f"[bold]{fleet.name}[/bold] v{fleet.version}\n"
        f"Client: {fleet.client}\n"
        f"{fleet.description}",
        title="Fleet Status",
    ))

    table = Table(show_header=True, header_style="bold cyan")
    table.add_column("Agent")
    table.add_column("Role")
    table.add_column("Skills")
    table.add_column("Workspace")

    for agent in fleet.agents:
        workspace = Path(fleet.defaults.workspace_base) / f"workspace-{agent.id}"
        ws_status = "[green]✓[/green]" if workspace.exists() else "[red]✗[/red]"
        role = "[magenta]orchestrator[/magenta]" if agent.orchestrator else "specialist"
        skills = ", ".join(
            f"{s.name}{'@' + s.version if s.version else ''}"
            for s in agent.skills
        ) or "—"
        table.add_row(
            f"{agent.emoji} {agent.name}",
            role,
            skills,
            f"{ws_status} {workspace}",
        )

    console.print(table)


# ── push subcommands ──────────────────────────────────────────────────────────

@push_app.command("skill")
def push_skill(
    skill_name: str = typer.Argument(..., help="Skill name to push"),
    config: Path = typer.Option(Path("fleet.yaml"), "--config", "-c"),
    agent_id: Optional[str] = typer.Option(None, "--agent", "-a", help="Target agent ID"),
    all_agents: bool = typer.Option(False, "--all", help="Push to all agents"),
    version: Optional[str] = typer.Option(None, "--version", "-v", help="Skill version to push"),
    force: bool = typer.Option(False, "--force", help="Push even if version is pinned"),
):
    """Push a skill to one or more agents."""
    from ..runtime.watcher import SkillsWatcher

    fleet = _load_fleet(config)
    watcher = SkillsWatcher(fleet)

    targets = []
    if all_agents:
        targets = [a.id for a in fleet.agents]
    elif agent_id:
        targets = [agent_id]
    else:
        console.print("[red]Error:[/red] specify --agent <id> or --all")
        raise typer.Exit(1)

    for tid in targets:
        watcher.push_skill(tid, skill_name, version)


@push_app.command("plugin")
def push_plugin(
    plugin_name: str = typer.Argument(..., help="Plugin name to push"),
    config: Path = typer.Option(Path("fleet.yaml"), "--config", "-c"),
    agent_id: Optional[str] = typer.Option(None, "--agent", "-a", help="Target agent ID"),
    all_agents: bool = typer.Option(False, "--all", help="Push to all agents"),
):
    """Push a plugin to one or more agents (updates fleet config)."""
    fleet = _load_fleet(config)

    targets = []
    if all_agents:
        targets = fleet.agents
    elif agent_id:
        agent = fleet.get_agent(agent_id)
        if not agent:
            console.print(f"[red]Agent {agent_id} not found[/red]")
            raise typer.Exit(1)
        targets = [agent]
    else:
        console.print("[red]Error:[/red] specify --agent <id> or --all")
        raise typer.Exit(1)

    for agent in targets:
        if plugin_name not in agent.plugins:
            agent.plugins.append(plugin_name)
            console.print(f"[green]✓[/green] Added plugin [bold]{plugin_name}[/bold] to {agent.emoji} {agent.name}")
        else:
            console.print(f"[dim]Plugin {plugin_name} already in {agent.name}[/dim]")

    console.print("\n[dim]Run [bold]fleetmind render[/bold] to update openclaw.json[/dim]")


# ── agent subcommands ─────────────────────────────────────────────────────────

@agent_app.command("list")
def agent_list(
    config: Path = typer.Option(Path("fleet.yaml"), "--config", "-c"),
):
    """List all agents in the fleet."""
    fleet = _load_fleet(config)

    for agent in fleet.agents:
        role = "orchestrator" if agent.orchestrator else "specialist"
        console.print(f"  {agent.emoji} [bold]{agent.name}[/bold] ({agent.id}) — {role}")


@agent_app.command("info")
def agent_info(
    agent_id: str = typer.Argument(..., help="Agent ID"),
    config: Path = typer.Option(Path("fleet.yaml"), "--config", "-c"),
):
    """Show details for a specific agent."""
    fleet = _load_fleet(config)
    agent = fleet.get_agent(agent_id)

    if not agent:
        console.print(f"[red]Agent '{agent_id}' not found.[/red]")
        console.print(f"Available: {', '.join(a.id for a in fleet.agents)}")
        raise typer.Exit(1)

    workspace = Path(fleet.defaults.workspace_base) / f"workspace-{agent.id}"
    console.print(Panel(
        f"[bold]{agent.emoji} {agent.name}[/bold] ({agent.id})\n"
        f"Role: {'orchestrator' if agent.orchestrator else 'specialist'}\n"
        f"Model: {agent.model or fleet.defaults.model}\n"
        f"Description: {agent.description}\n\n"
        f"Slack account: {agent.slack.account_id}\n"
        f"Skills: {', '.join(s.name + ('@' + s.version if s.version else '') for s in agent.skills) or '—'}\n"
        f"Plugins: {', '.join(agent.plugins) or '—'}\n"
        f"Can send to: {', '.join(agent.agent_to_agent.can_send_to) or '—'}\n\n"
        f"Workspace: {workspace} ({'exists' if workspace.exists() else 'not provisioned'})",
        title=f"Agent: {agent.id}",
    ))


# ── secrets subcommands ───────────────────────────────────────────────────────

@secrets_app.command("set")
def secrets_set(
    key: str = typer.Argument(..., help="Secret key"),
    value: str = typer.Argument(..., help="Secret value"),
):
    """Store a secret in the fleet's local secret store."""
    secrets = _load_secrets()
    secrets[key] = value
    _save_secrets(secrets)
    # Also set in current environment for immediate use
    os.environ[key] = value
    console.print(f"[green]✓[/green] Secret [bold]{key}[/bold] stored.")


@secrets_app.command("list")
def secrets_list():
    """List stored secret keys (values are never shown)."""
    secrets = _load_secrets()
    if not secrets:
        console.print("[dim]No secrets stored.[/dim]")
        return
    console.print("[bold]Stored secrets:[/bold]")
    for key in sorted(secrets):
        console.print(f"  [cyan]{key}[/cyan] = [dim]***[/dim]")


@secrets_app.command("export")
def secrets_export():
    """Export secrets as shell export statements."""
    secrets = _load_secrets()
    for key, value in secrets.items():
        print(f"export {key}={value!r}")


def main():
    # Load secrets into env before running any command
    try:
        for key, value in _load_secrets().items():
            if key not in os.environ:
                os.environ[key] = value
    except Exception:
        pass
    app()
