"""
FleetMind renderer — generates openclaw.json and terraform vars from fleet config.
"""

from __future__ import annotations
import json
from pathlib import Path

from ..coordinator.config import FleetConfig


def render_openclaw_json(fleet: FleetConfig) -> dict:
    """Generate the full OpenClaw config dict from a fleet definition."""
    oc = fleet.openclaw
    defaults = fleet.defaults

    # Build agents list
    agents_list = []
    for agent in fleet.agents:
        model = agent.model or defaults.model
        workspace = defaults.workspace_base + "/workspace-" + agent.id
        agent_dir = defaults.workspace_base + "/agents/" + agent.id + "/agent"
        entry = {
            "id": agent.id,
            "name": agent.name,
            "workspace": workspace,
            "agentDir": agent_dir,
            "model": {"primary": model},
        }
        if agent.orchestrator:
            entry["default"] = True
        agents_list.append(entry)

    # Build bindings
    bindings = []
    for agent in fleet.agents:
        bindings.append({
            "agentId": agent.id,
            "match": {
                "channel": "slack",
                "accountId": agent.slack.account_id,
            },
        })

    # Build Slack accounts
    slack_accounts = {}
    for agent in fleet.agents:
        slack_accounts[agent.slack.account_id] = {
            "enabled": True,
            "botToken": agent.slack.bot_token,
            "appToken": agent.slack.app_token,
            "webhookPath": "/slack/" + agent.slack.account_id,
            "groupPolicy": "open",
        }

    # Build agentToAgent allow list
    a2a_entries = []
    for agent in fleet.agents:
        for target_id in agent.agent_to_agent.can_send_to:
            pair = {"from": agent.id, "to": target_id}
            if pair not in a2a_entries:
                a2a_entries.append(pair)

    config = {
        "agents": {
            "defaults": {
                "model": {"primary": defaults.model},
            },
            "list": agents_list,
        },
        "bindings": bindings,
        "tools": {
            "profile": oc.tools_profile,
            "agentToAgent": {
                "enabled": True,
                "allow": a2a_entries,
            },
            "web": {
                "search": {
                    "enabled": oc.web_search_enabled,
                    "provider": oc.web_search_provider,
                }
            },
        },
        "session": {
            "dmScope": oc.dm_scope,
        },
        "channels": {
            "slack": {
                "mode": oc.slack_mode,
                "enabled": True,
                "typingReaction": oc.typing_reaction,
                "ackReaction": oc.ack_reaction,
                "allowBots": oc.allow_bots,
                "historyLimit": oc.history_limit,
                "streaming": {
                    "mode": oc.streaming_mode,
                    "nativeTransport": True,
                },
                "replyToModeByChatType": {
                    "channel": "all",
                },
                "accounts": slack_accounts,
            }
        },
        "gateway": {
            "port": oc.gateway.port,
            "mode": oc.gateway.mode,
            "bind": oc.gateway.bind,
        },
        "hooks": {
            "internal": {
                "enabled": True,
                "entries": {
                    "boot-md": {"enabled": True},
                    "session-memory": {"enabled": True},
                    "command-logger": {"enabled": True},
                },
            }
        },
        "plugins": {
            "entries": _build_plugins(fleet),
        },
        "commands": {
            "native": "auto",
            "nativeSkills": "auto",
            "restart": True,
        },
    }

    return config


def _build_plugins(fleet: FleetConfig) -> dict:
    """Collect all unique plugins across all agents and build plugin entries."""
    all_plugins: set[str] = set()
    for agent in fleet.agents:
        all_plugins.update(agent.plugins)

    entries = {}
    for plugin in sorted(all_plugins):
        entries[plugin] = {"enabled": True}

    return entries


def render_terraform_vars(fleet: FleetConfig) -> str:
    """Emit a .tfvars file for consumption by openclaw-terraform."""
    agent_ids = ", ".join('"' + a.id + '"' for a in fleet.agents)
    lines = [
        "# Auto-generated by FleetMind — do not edit manually",
        "# Fleet: " + fleet.name + " v" + fleet.version,
        "",
        'fleet_name    = "' + fleet.name + '"',
        'fleet_client  = "' + fleet.client + '"',
        "agent_count   = " + str(len(fleet.agents)),
        "agent_ids     = [" + agent_ids + "]",
        "",
        "# Agent model assignments",
    ]
    for agent in fleet.agents:
        model = agent.model or fleet.defaults.model
        lines.append('agent_' + agent.id + '_model = "' + model + '"')

    return "\n".join(lines) + "\n"


def write_outputs(fleet: FleetConfig, base_dir: Path | None = None) -> dict:
    """Write all rendered outputs and return a map of output name -> path."""
    base = base_dir or Path(".")
    written = {}

    # openclaw.json
    oc_path = base / fleet.outputs.openclaw_json
    oc_path.parent.mkdir(parents=True, exist_ok=True)
    oc_path.write_text(json.dumps(render_openclaw_json(fleet), indent=2))
    written["openclaw_json"] = oc_path

    # terraform vars
    tf_path = base / fleet.outputs.terraform_vars
    tf_path.parent.mkdir(parents=True, exist_ok=True)
    tf_path.write_text(render_terraform_vars(fleet))
    written["terraform_vars"] = tf_path

    return written
