#!/bin/bash
set -euo pipefail

AGENT_NAME="${agent_name}"
AGENT_PORT="${agent_port}"
FLEET_NAME="${fleet_name}"
OPENCLAW_IMAGE="${openclaw_image}"
AWS_REGION="${aws_region}"
WORKSPACE_DIR="/opt/openclaw/workspace"
SECRETS_ENV="/run/openclaw-secrets.env"

# ── Logging ───────────────────────────────────────────────────────────────────
exec > >(tee /var/log/openclaw-bootstrap.log | logger -t openclaw-bootstrap) 2>&1
echo "[bootstrap] Starting OpenClaw agent: $AGENT_NAME"

# ── System updates + Docker ───────────────────────────────────────────────────
dnf update -y
dnf install -y docker aws-cli

systemctl enable docker
systemctl start docker

# ── AWS CLI v2 (AL2023 ships v1; upgrade if needed) ───────────────────────────
if ! aws --version 2>&1 | grep -q "aws-cli/2"; then
  echo "[bootstrap] Upgrading to AWS CLI v2"
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
  unzip -q /tmp/awscliv2.zip -d /tmp
  /tmp/aws/install --update
  rm -rf /tmp/aws /tmp/awscliv2.zip
fi

# ── EBS workspace volume (/dev/xvdf → /opt/openclaw/workspace) ────────────────
# Wait for device to appear (EBS attach can take a few seconds)
for i in $(seq 1 30); do
  [ -b /dev/xvdf ] && break
  echo "[bootstrap] Waiting for EBS volume... ($i/30)"
  sleep 2
done

if [ ! -b /dev/xvdf ]; then
  echo "[bootstrap] ERROR: EBS volume /dev/xvdf not found after 60s" >&2
  exit 1
fi

# Format only if the volume is blank (preserves data on instance replacement)
if ! blkid /dev/xvdf > /dev/null 2>&1; then
  echo "[bootstrap] Formatting EBS volume (first use)"
  mkfs.ext4 -F /dev/xvdf
else
  echo "[bootstrap] EBS volume already formatted — skipping mkfs (data preserved)"
fi

mkdir -p "$WORKSPACE_DIR"

# Add to fstab for persistence across reboots
FSTAB_ENTRY="/dev/xvdf $WORKSPACE_DIR ext4 defaults,nofail 0 2"
if ! grep -qF "$FSTAB_ENTRY" /etc/fstab; then
  echo "$FSTAB_ENTRY" >> /etc/fstab
fi

mount "$WORKSPACE_DIR" || mount -a
echo "[bootstrap] Workspace mounted at $WORKSPACE_DIR"

# ── Secret fetch script ───────────────────────────────────────────────────────
cat > /usr/local/bin/fetch-openclaw-secrets.sh << 'FETCH_EOF'
#!/bin/bash
set -euo pipefail

FLEET_NAME="FLEET_NAME_PLACEHOLDER"
AGENT_NAME="AGENT_NAME_PLACEHOLDER"
AWS_REGION="AWS_REGION_PLACEHOLDER"
SECRETS_ENV="SECRETS_ENV_PLACEHOLDER"

# Fetch shared ANTHROPIC_KEY
ANTHROPIC_SECRET=$(aws secretsmanager get-secret-value \
  --secret-id "$FLEET_NAME/shared/anthropic" \
  --region "$AWS_REGION" \
  --query SecretString --output text 2>/dev/null || echo "{}")

# Fetch per-agent Slack tokens
AGENT_SECRET=$(aws secretsmanager get-secret-value \
  --secret-id "$FLEET_NAME/agents/$AGENT_NAME/slack" \
  --region "$AWS_REGION" \
  --query SecretString --output text 2>/dev/null || echo "{}")

# Write env file (readable only by root)
install -m 600 /dev/null "$SECRETS_ENV"
echo "# Auto-generated by fetch-openclaw-secrets.sh — do not edit" > "$SECRETS_ENV"

# Parse JSON and write env vars
python3 - << PYEOF >> "$SECRETS_ENV"
import json, sys

def parse_secret(raw):
    try:
        return json.loads(raw)
    except:
        return {}

anthropic = parse_secret('''$ANTHROPIC_SECRET''')
agent = parse_secret('''$AGENT_SECRET''')

combined = {**anthropic, **agent}
for k, v in combined.items():
    print(f"{k}={v}")
PYEOF

echo "[secrets] Wrote $(grep -c = $SECRETS_ENV) vars to $SECRETS_ENV"
FETCH_EOF

# Substitute placeholders
sed -i \
  -e "s|FLEET_NAME_PLACEHOLDER|$FLEET_NAME|g" \
  -e "s|AGENT_NAME_PLACEHOLDER|$AGENT_NAME|g" \
  -e "s|AWS_REGION_PLACEHOLDER|$AWS_REGION|g" \
  -e "s|SECRETS_ENV_PLACEHOLDER|$SECRETS_ENV|g" \
  /usr/local/bin/fetch-openclaw-secrets.sh

chmod +x /usr/local/bin/fetch-openclaw-secrets.sh

# ── systemd service ───────────────────────────────────────────────────────────
cat > /etc/systemd/system/openclaw-agent.service << EOF
[Unit]
Description=OpenClaw Agent ($AGENT_NAME)
After=docker.service network-online.target
Requires=docker.service
Wants=network-online.target

[Service]
Type=simple
Restart=always
RestartSec=10
StartLimitBurst=5
StartLimitIntervalSec=60

# Fetch fresh secrets before each start
ExecStartPre=/usr/local/bin/fetch-openclaw-secrets.sh

ExecStart=/usr/bin/docker run --rm \\
  --name openclaw-$AGENT_NAME \\
  -v $WORKSPACE_DIR:/workspace \\
  -p $AGENT_PORT:$AGENT_PORT \\
  --env-file $SECRETS_ENV \\
  -e OPENCLAW_WORKSPACE=/workspace \\
  -e OPENCLAW_PORT=$AGENT_PORT \\
  -e AGENT_NAME=$AGENT_NAME \\
  $OPENCLAW_IMAGE

ExecStop=/usr/bin/docker stop openclaw-$AGENT_NAME

StandardOutput=journal
StandardError=journal
SyslogIdentifier=openclaw-$AGENT_NAME

[Install]
WantedBy=multi-user.target
EOF

# ── Pull image + start ────────────────────────────────────────────────────────
echo "[bootstrap] Pulling $OPENCLAW_IMAGE"
docker pull "$OPENCLAW_IMAGE" || true  # Non-fatal: service will retry

systemctl daemon-reload
systemctl enable openclaw-agent
systemctl start openclaw-agent

echo "[bootstrap] Done. Agent $AGENT_NAME started on port $AGENT_PORT"
