import { Command } from "commander";
import fs from "node:fs";
import { log } from "../../utils/log.js";

const TEMPLATE = `# fleet.yaml — FleetMind fleet definition
# Generated by: fleetmind init
#
# Fill in your values and run: fleetmind deploy

fleet:
  name: {NAME}
  version: "1.0.0"
  client: {CLIENT}
  description: ""

skills_repo:
  url: ""               # https://github.com/your-org/your-skills-repo
  branch: main
  poll_interval: 60s
  # local: ./skills     # Use local skills dir (dev mode)

secrets:
  provider: env

# ── Targets (runtime hosts) ───────────────────────────────────────────────────
# Where each agent runs, how to reach it, and how to (re)start its gateway.
# Agents reference a target by id (see agents.defaults.target below). The
# \`provider\` discriminates the host type and selects the per-host block:
#   aws-ssm → EC2 reached via SSM (requires aws.region)
#   ssh     → Mac mini / bare metal / VMware guest (requires ssh.host, ssh.user)
#   local   → the operator machine (dev / single-box deploys)
targets:
  conductor-host:
    provider: aws-ssm
    os: linux
    service_manager: systemd
    workspace_base: /home/openclaw/.openclaw/workspace
    aws:
      region: us-west-2          # edit to your region
      # runtime_user: openclaw   # default; set ec2-user only for legacy hosts
  # Example of a non-AWS host (e.g. a Mac mini) — uncomment and point an agent at it:
  # mac-lab-1:
  #   provider: ssh
  #   os: macos
  #   service_manager: launchd
  #   workspace_base: /Users/openclaw/.openclaw
  #   ssh:
  #     host: mac-lab-1.local
  #     user: openclaw
  # Example of a local (operator-machine) host:
  # local-box:
  #   provider: local
  #   os: macos
  #   service_manager: launchd
  #   workspace_base: ~/.openclaw

agents:
  defaults:
    model: anthropic/claude-sonnet-4-6
    target: conductor-host       # default host for agents that don't set their own
    plugins:
      - anthropic

  list:
    - id: conductor
      name: Conductor
      emoji: 🎼
      role: pm
      description: "Orchestrator. Routes requests to specialist agents."
      orchestrator: true
      persona:
        soul: |
          You are Conductor, an orchestrating AI that coordinates a fleet of specialists.
          Delegate to specialists via sessions_send. Synthesize results for the user.
      channels:
        - provider: slack
          account_id: conductor
          bot_token: \${CONDUCTOR_BOT_TOKEN}
          app_token: \${CONDUCTOR_APP_TOKEN}
      skills:
        - name: bot-delegation
          source: fleetmind
        - name: worker-self-start
          source: fleetmind
      plugins: [anthropic]
      agent_to_agent:
        can_send_to: []

outputs:
  openclaw_json: ./rendered/openclaw.json
  terraform_vars: ./rendered/fleet.derived.tfvars
  workspace_manifests: ./rendered/workspaces/

openclaw:
  gateway:
    port: 18789
    mode: local
    bind: loopback
  session:
    dm_scope: per-channel-peer
  tools:
    profile: coding
  slack:
    mode: socket
    typing_reaction: thinking_face
    ack_reaction: eyes
    allow_bots: true
    history_limit: 111
`;

/** Render the scaffold template with a fleet name + client substituted in.
 *  Exported so tests can round-trip it through the loader. */
export function renderInitTemplate(name: string, client: string): string {
  return TEMPLATE.replace("{NAME}", name).replace("{CLIENT}", client);
}

export function registerInit(program: Command): void {
  program
    .command("init")
    .description("Scaffold a new fleet.yaml in the current directory")
    .option("-n, --name <name>", "Fleet name", "my-fleet")
    .option("-c, --client <client>", "Client name")
    .option("-o, --output <file>", "Output file", "fleet.yaml")
    .addHelpText('after', `
Examples:
  # Scaffold a fleet.yaml with defaults in the current directory
  $ fleetmind init

  # Scaffold with a specific fleet name
  $ fleetmind init --name acme-bots

  # Scaffold with fleet name and client, writing to a custom file
  $ fleetmind init --name acme-bots --client acme --output my-fleet.yaml
`)
    .action((opts) => {
      const output = opts.output as string;
      if (fs.existsSync(output)) {
        log.warn(`${output} already exists — use a different --output path to avoid overwriting.`);
        process.exit(1);
      }

      const name = opts.name as string;
      const client = (opts.client as string) ?? name;
      const content = renderInitTemplate(name, client);

      fs.writeFileSync(output, content, "utf-8");
      fs.mkdirSync("rendered", { recursive: true });

      // .gitignore
      const ignore = ["fleet.yaml", "rendered/openclaw.json", ".env"];
      const giPath = ".gitignore";
      if (fs.existsSync(giPath)) {
        const existing = fs.readFileSync(giPath, "utf-8");
        const missing = ignore.filter((l) => !existing.includes(l));
        if (missing.length) fs.appendFileSync(giPath, "\n" + missing.join("\n") + "\n");
      } else {
        fs.writeFileSync(giPath, ignore.join("\n") + "\n");
      }

      log.ok(`Created ${output}`);
      log.info("\nNext steps:");
      log.info("  1. Edit fleet.yaml — add agents, Slack tokens, skills");
      log.info("  2. fleetmind secrets set CONDUCTOR_BOT_TOKEN xoxb-...");
      log.info("  3. fleetmind deploy");
    });
}
